### ISSUE TITLE
Knitting as rdocx_document fails when source file is .R

### ISSUE THREAD

**Issue by WilDoane** [davidgohel/officedown#48]
Given two predominate formats for source documents to be knitted (1) .Rmd RMarkdown files and (2) .R R scripts, knitting fails when the source document is .R and the output format is officedown::rdocx_document.

*.Rmd Style*
````
---
output: officedown::rdocx_document
---

```{r}
mtcars
```
````

*.R Style*
```
#' ---
#' output: officedown::rdocx_document
#' ---

mtcars
```

Calling rmarkdown::render() on .Rmd style documents succeeds for both the word_document and officedown::rdocx_document output formats.

Calling rmarkdown::render() on .R style documents succeeds for the word_document output format, but fails for officedown::rdocx_document format documents.

&nbsp;   | .Rmd | .R
--- | ------ | ----------
word_document | Success | Success
rdocx_document | Success | Fail

```
# Success
rmarkdown::render('reprex.Rmd',  encoding = 'UTF-8', output_format = 'officedown::rdocx_document')

reprex.Rmd -> 
  (@314) reprex.knit.md -> 
    (@361) reprex.utf8.md -> 
      (@452) repres.docx

# Success
rmarkdown::render('reprex.R',  encoding = 'UTF-8', output_format = 'word_document')

reprex.R -> 
  (@92) reprex.spin.R -> 
    (@94) reprex.spin.Rmd -> 
      (@314) reprex.knit.md -> 
        (@361) reprex.utf8.md -> 
          (@452) repres.docx

# Failure
rmarkdown::render('reprex.R',  encoding = 'UTF-8', output_format = 'officedown::rdocx_document')

reprex.R -> 
  (@92) reprex.spin.R -> 
    (@94) reprex.spin.Rmd -> 
      (@314) reprex.knit.md -> 
      FAIL

Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file 'reprex.spin.knit.md': No such file or directory
```

The failure case occurs when rmarkdown::render() calls officedown's post_knit hook with input_file = "reprex.spin.Rmd"

https://github.com/davidgohel/officedown/blob/abac21abc42ce02f6a745e02f6fd70c28ddb41b3/R/rdocx_document.R#L342

The hook code creates an expected output_file value of "reprex.spin.knit.md", which doesn't exist.

I would prep a PR, but I'm not sure how best to handle this without breaking any other execution paths or being hackish about the expected output filename.

Component | Versions
---------- | -----------
OS | both MacOS and Windows 10
R | 3.6.3 and 4.0.3
knitr | 1.30
rmarkdown | 2.5
officedown | 0.2.1.0
officer | 0.3.15

**Comment by davidgohel** [comment]
Hi, I think it is related to #38 

I will fix it, thanks

**Comment by davidgohel** [comment]
This is solved now. 

I did not know it was possible to have an R file instead of Rmd, thanks for that!

**Comment by WilDoane** [comment]
The filename problem appears to persist even with the latest R, rmarkdown, knitr, and (from github) officedown installed.

Given an .R script:
```
#' ---
#' output: officedown::rdocx_document
#' ---

mtcars
```
knitted from rstudio

I still receive the same error:
```
processing file: reprex-officedown.spin.Rmd
  |.......................                                               |  33%
  ordinary text without R code

  |...............................................                       |  67%
label: unnamed-chunk-1
  |......................................................................| 100%
  ordinary text without R code


output file: reprex-officedown.knit.md

Error in file(con, "r") : cannot open the connection
Calls: <Anonymous> ... call_post_knit_handler -> <Anonymous> -> readLines -> file
In addition: Warning message:
In file(con, "r") :
  cannot open file './reprex-officedown.spin.knit.md': No such file or directory
Execution halted
```


```
- Session info -----------------------------------------------------------------------------------
 setting  value                       
 version  R version 4.0.5 (2021-03-31)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/New_York            
 date     2021-05-17                  

- Packages ---------------------------------------------------------------------------------------
 package     * version   date       lib source                                
 cachem        1.0.5     2021-05-15 [1] CRAN (R 4.0.4)                        
 callr         3.7.0     2021-04-20 [1] CRAN (R 4.0.5)                        
 cli           2.5.0     2021-04-26 [1] CRAN (R 4.0.5)                        
 crayon        1.4.1     2021-02-08 [1] CRAN (R 4.0.3)                        
 curl          4.3.1     2021-04-30 [1] CRAN (R 4.0.5)                        
 desc          1.3.0     2021-03-05 [1] CRAN (R 4.0.4)                        
 devtools      2.4.1     2021-05-05 [1] CRAN (R 4.0.5)                        
 digest        0.6.27    2020-10-24 [1] CRAN (R 4.0.3)                        
 ellipsis      0.3.2     2021-04-29 [1] CRAN (R 4.0.5)                        
 evaluate      0.14      2019-05-28 [1] CRAN (R 4.0.2)                        
 fastmap       1.1.0     2021-01-25 [1] CRAN (R 4.0.3)                        
 fs            1.5.0     2020-07-31 [1] CRAN (R 4.0.2)                        
 gdtools       0.2.3     2021-01-06 [1] CRAN (R 4.0.3)                        
 glue          1.4.2     2020-08-27 [1] CRAN (R 4.0.2)                        
 highr         0.9       2021-04-16 [1] CRAN (R 4.0.5)                        
 htmltools     0.5.1.1   2021-01-22 [1] CRAN (R 4.0.3)                        
 jsonlite      1.7.2     2020-12-09 [1] CRAN (R 4.0.3)                        
 knitr         1.33      2021-04-24 [1] CRAN (R 4.0.5)                        
 lattice       0.20-41   2020-04-02 [2] CRAN (R 4.0.5)                        
 lifecycle     1.0.0     2021-02-15 [1] CRAN (R 4.0.4)                        
 magrittr      2.0.1     2020-11-17 [1] CRAN (R 4.0.3)                        
 Matrix        1.3-2     2021-01-06 [2] CRAN (R 4.0.5)                        
 memoise       2.0.0     2021-01-26 [1] CRAN (R 4.0.3)                        
 officedown  * 0.2.3.001 2021-05-17 [1] Github (davidgohel/officedown@f3be474)
 officer     * 0.3.18    2021-04-02 [1] CRAN (R 4.0.5)                        
 pkgbuild      1.2.0     2020-12-15 [1] CRAN (R 4.0.3)                        
 pkgload       1.2.1     2021-04-06 [1] CRAN (R 4.0.5)                        
 png           0.1-7     2013-12-03 [1] CRAN (R 4.0.0)                        
 prettyunits   1.1.1     2020-01-24 [1] CRAN (R 4.0.2)                        
 processx      3.5.2     2021-04-30 [1] CRAN (R 4.0.5)                        
 ps            1.6.0     2021-02-28 [1] CRAN (R 4.0.4)                        
 purrr         0.3.4     2020-04-17 [1] CRAN (R 4.0.2)                        
 R6            2.5.0     2020-10-28 [1] CRAN (R 4.0.3)                        
 rappdirs      0.3.3     2021-01-31 [1] CRAN (R 4.0.3)                        
 Rcpp          1.0.6     2021-01-15 [1] CRAN (R 4.0.3)                        
 remotes       2.3.0     2021-04-01 [1] CRAN (R 4.0.5)                        
 reticulate    1.20      2021-05-03 [1] CRAN (R 4.0.5)                        
 rlang         0.4.11    2021-04-30 [1] CRAN (R 4.0.5)                        
 rmarkdown     2.8       2021-05-07 [1] CRAN (R 4.0.5)                        
 rprojroot     2.0.2     2020-11-15 [1] CRAN (R 4.0.3)                        
 rstudioapi    0.13      2020-11-12 [1] CRAN (R 4.0.3)                        
 rvg           0.2.5     2020-06-30 [1] CRAN (R 4.0.3)                        
 sessioninfo   1.1.1     2018-11-05 [1] CRAN (R 4.0.2)                        
 systemfonts   1.0.2     2021-05-11 [1] CRAN (R 4.0.5)                        
 testthat      3.0.2     2021-02-14 [1] CRAN (R 4.0.4)                        
 usethis       2.0.1     2021-02-10 [1] CRAN (R 4.0.3)                        
 uuid          0.1-4     2020-02-26 [1] CRAN (R 4.0.3)                        
 withr         2.4.2     2021-04-18 [1] CRAN (R 4.0.5)                        
 xfun          0.23      2021-05-15 [1] CRAN (R 4.0.4)                        
 xml2          1.3.2     2020-04-23 [1] CRAN (R 4.0.2)                        
 yaml          2.2.1     2020-02-01 [1] CRAN (R 4.0.2)                        
 zip           2.1.1     2020-08-27 [1] CRAN (R 4.0.2)                        

```

**Comment by seankross** [comment]
Same issue when the source file is `.md`. (I understand that rendering `.md` files may be outside the scope of this package, but I just wanted to make you aware)

```r
library(rmarkdown)
library(officedown)

writeLines(c("# Heading", "", "- item 1", "- item 2", ""), "test-file.md")

render("test-file.md", output_format = rdocx_document())
```

```
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file './test-file.knit.md': No such file or directory
```

**Comment by davidgohel** [comment]
It should be fixed now

**Comment by davidgohel** [comment]
@seankross your issue is also fixed (by the same solution)
